[package]
name = "basket"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "basket"

[features]
no-entrypoint = []
idl-build = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["token", "token-2022"] }
bytemuck = "1.13"